services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama-server
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    networks:
      - chat-network
    restart: unless-stopped

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: chat-backend
    ports:
      - "5000:5000"
    environment:
      - OLLAMA_HOST=ollama
      - OLLAMA_PORT=11434
      - MODEL_NAME=llama3.2
      - SECRET_KEY=priyank
    depends_on:
      - ollama
    networks:
      - chat-network
    restart: unless-stopped
    volumes:
      - ./backend:/app

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: chat-frontend
    ports:
      - "8501:8501"
    environment:
      - BACKEND_HOST=backend
      - BACKEND_PORT=5000
    depends_on:
      - backend
    networks:
      - chat-network
    restart: unless-stopped
    volumes:
      - ./frontend:/app

volumes:
  ollama_data:

networks:
  chat-network:
    driver: bridge